include::tiles/header.adoc[]
== Efficient Full Text Search With Vespa: Basic Start

=== About Vespa
Vespa is a full-featured search engine with full support for traditional information retrieval as well as modern vector embedding based techniques.
link:https://vespa.ai/[More]

=== Prerequisites
* link:https://docs.docker.com/engine/install/[Docker]
* link:https://docs.vespa.ai/en/vespa-cli.html[Vespa CLI]
* Download link:https://github.com/anton-kolhun/vespa-sample[Vespa Application Package] Sample

=== Start vespa container
----
docker run -d -p 8080:8080 -p 19071:19071 vespaengine/vespa
----

=== Deploy vespa application package (VAP)
- Navigate to the VAP

The key elements here are `book.sd` and `book_v1.xml`.
The first describes the schema of our search entity (book).
The latter builds a template of our search query: it's a full-text search based on 3 fields: title, tags and description

- Now deploy VAP as
----
vespa deploy book
----

=== Feed Documents
Once VAP gets up and running feed documents as:
----
vespa feed book/ext/docs.json
----

=== Search Documents
We can now execute search request as:
----
curl http://localhost:8080/search/ \
--header 'Content-Type: application/json' \
--data '{
    "queryProfile": "book_v1",
    "search_term": "Scott Fitzgerald",
    "query_filter": "AND year > 1800"
}'
----
or
----
curl http://localhost:8080/search/ \
--header 'Content-Type: application/json' \
--data '{
    "queryProfile": "book_v1",
    "search_term": "Diamond",
    "query_filter": "AND year > 1800"
}'
----
As expected, the both requests list Scott Fitzgerald's "The Diamond as Big as the Ritz" book

=== Summary
Great Start! Within several steps, we managed to run Vespa engine, index documents and perform search requests against them.

